FROM ubuntu:latest

ENV R_VERSION=devel
ENV R_HOME=/usr/local/lib/R
ENV TZ=Etc/EDT

COPY scripts/install_R_source.sh /rocker_scripts/install_R_source.sh

RUN /rocker_scripts/install_R_source.sh

ENV CRAN=https://cloud.r-project.org
ENV LANG=en_US.UTF-8

COPY scripts /rocker_scripts

RUN /rocker_scripts/setup_R.sh

RUN apt-get -yq update
RUN apt-get -yq install python3
RUN apt-get -yq install pip

RUN update-ca-certificates \
&& pip install --upgrade pip setuptools six \
&& pip install --no-cache-dir gevent==21.12.0 flask==2.1.2

ENV FLASK_PROXY_PORT 8080

RUN mkdir -p /actionProxy/owplatform
ADD actionproxy.py /actionProxy/
ADD owplatform/__init__.py /actionProxy/owplatform/
ADD owplatform/knative.py /actionProxy/owplatform/
ADD owplatform/openwhisk.py /actionProxy/owplatform/

RUN mkdir -p /action
ADD stub.sh /action/exec
RUN chmod +x /action/exec

CMD ["/bin/bash", "-c", "cd actionProxy && python3 actionproxy.py"]
